kind: Pod
apiVersion: v1
metadata:
  name: biobert
  namespace: $NS
  labels:
    app: biobert
spec:
  imagePullSecrets:             
  - name: imagepull-secret
  containers:
  - name: biobert
    image: $HW_IMAGE_PREFIX/biobert:0.1-gpu
    command: ["sleep", "4000"]
    resources:
      limits:
        cpu: 4
        memory: 32Gi
        nvidia.com/gpu-tesla-v100-16GB: 1
      requests:
        cpu: 4
        memory: 32Gi
        nvidia.com/gpu-tesla-v100-16GB: 1
    volumeMounts:                 
    - mountPath: "/data"
      name: pvc-biobert-data
  volumes:
    - name: pvc-biobert-data
      persistentVolumeClaim:
        claimName: biobert-data
