kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: biobert-data
  namespace: $NS
  labels:
    app: biobert
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sas
